name: "godot-ci export"
on:
  push:
    branches:
      - release

env:
  GODOT_VERSION: 3.3.1
  EXPORT_NAME: war-pigs

jobs:
  export-deploy-windows:
    name: Windows Export and Deploy
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.3.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          # cd $EXPORT_NAME
          godot -v --export "Windows Desktop" build/windows/$EXPORT_NAME.exe
      - name: Deployt to Itch
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
            BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
            CHANNEL: windows
            ITCH_GAME: war-pigs
            ITCH_USER: Oeslian
            PACKAGE: build/windows


  export-deploy-linux:
    name: Linux Export and Deploy
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.3.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Linux Build
        run: |
          mkdir -v -p build/linux
          # cd $EXPORT_NAME
          godot -v --export "Linux/X11" build/linux/$EXPORT_NAME.x86_64
      - name: Deploy to Itch
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
            BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
            CHANNEL: linux
            ITCH_GAME: war-pigs
            ITCH_USER: Oeslian
            PACKAGE: build/linux


#  export-deploy-web:
#    name: Web Export and Deploy
#    runs-on: ubuntu-latest
#    container:
#      image: barichello/godot-ci:3.3.1
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#        with:
#          lfs: true
#      - name: Setup
#        run: |
#          mkdir -v -p ~/.local/share/godot/templates
#          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
#      - name: Web Build
#        run: |
#          mkdir -v -p build/web
#          # cd $EXPORT_NAME
#          godot -v --export "HTML5" build/web/index.html
#      - name: Deploy to Itch
#        uses: josephbmanley/butler-publish-itchio-action@master
#        env:
#            BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
#            CHANNEL: web
#            ITCH_GAME: War Pigs
#            ITCH_USER: Oeslian
#            PACKAGE: build/web
      # Installing rsync is needed in order to deploy to GitHub Pages. Without it, the build will fail.
      #- name: Install rsync 📚
      #run: |
      #   apt-get update && apt-get install -y rsync
      #- name: Deploy to GitHub Pages 🚀
      #  uses: JamesIves/github-pages-deploy-action@releases/v3
      #  with:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #    BRANCH: gh-pages # The branch the action should deploy to.
      #    FOLDER: build/web # The folder the action should deploy.


  export-deploy-mac:
    name: Mac Export and Deploy
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.3.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Mac Build
        run: |
          mkdir -v -p build/mac
          godot -v --export "Mac OSX" build/mac/$EXPORT_NAME.zip
      - name: Deploy to Itch
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
            BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
            CHANNEL: mac
            ITCH_GAME: war-pigs
            ITCH_USER: Oeslian
            PACKAGE: build/mac
